const ERROR_CODES = {
  UNKWON_ERROR : "UNKWON_ERROR",
  VALIDATION_ERROR : "VALIDATION_ERROR",
  TOO_MANY_REQUEST : "TOO_MANY_REQUEST",

  EMAIL_ALREADY_REGISTERED : "EMAIL_ALREADY_REGISTERED"
}

export default ERROR_CODES;