const ERROR_CODES = {
  REQUEST_ERROR : "REQUEST_ERROR",
  UNKWON_ERROR : "UNKWON_ERROR",
  VALIDATION_ERROR : "VALIDATION_ERROR",
  TOO_MANY_REQUEST : "TOO_MANY_REQUEST",
  NOT_FOUND : "NOT_FOUND",

  ACCOUNT_BLOCKED : "ACCOUNT_BLOCKED",
  ACCOUNT_REQUIRES_SET_UP : "ACCOUNT_REQUIRES_SET_UP", 

  EXPIRED : "EXPIRED",

  INCORRECT_PIN : "INCORRECT_PIN",
  INVALID_CREDENTIALS : "INVALID_CREDENTIALS", 
  EMAIL_ALREADY_REGISTERED : "EMAIL_ALREADY_REGISTERED",
  USERNAME_ALREADY_TAKEN : "USERNAME_ALREADY_TAKEN",
}

export default ERROR_CODES;