const ERROR_CODES = {
  REQUEST_ERROR : "REQUEST_ERROR",
  UNKWON_ERROR : "UNKWON_ERROR",
  VALIDATION_ERROR : "VALIDATION_ERROR",
  TOO_MANY_REQUEST : "TOO_MANY_REQUEST",
  NOT_FOUND : "NOT_FOUND",

  EXPIRED : "EXPIRED",

  INCORRECT_PIN : "INCORRECT_PIN",
  INVALID_CREDENTIALS : "INVALID_CREDENTIALS", 
  EMAIL_ALREADY_REGISTERED : "EMAIL_ALREADY_REGISTERED"
}

export default ERROR_CODES;