import { MEMBER_ROLES } from "../models/member.model.js";
import { PROJECT_ACTIONS } from "../models/project.model.js";

export const ROLE_PERMISSIONS = Object.freeze({
  [MEMBER_ROLES.LEADER]: Object.freeze([
    PROJECT_ACTIONS.FETCH_PROJECT,
    PROJECT_ACTIONS.FETCH_MEMBERS,
    PROJECT_ACTIONS.FETCH_TASKS,
    PROJECT_ACTIONS.UPDATE_PROJECT_DETAILS,
    PROJECT_ACTIONS.UPDATE_PROJECT_STATUS,
    PROJECT_ACTIONS.UPDATE_PROJECT_SETTINGS,
    PROJECT_ACTIONS.ARCHIVE_PROJECT,
    PROJECT_ACTIONS.DELETE_PROJECT,
    PROJECT_ACTIONS.INVITE_MEMBER,
    PROJECT_ACTIONS.KICK_MEMBER,
    PROJECT_ACTIONS.TRANSFER_LEADERSHIP,
    PROJECT_ACTIONS.CREATE_TASK,
    PROJECT_ACTIONS.UPDATE_TASK,
    PROJECT_ACTIONS.ASSIGN_TASK,
    PROJECT_ACTIONS.DELETE_TASK,
  ]),
  
  [MEMBER_ROLES.MEMBER]: Object.freeze([
    PROJECT_ACTIONS.FETCH_PROJECT,
    PROJECT_ACTIONS.FETCH_MEMBERS,
    PROJECT_ACTIONS.FETCH_TASKS,
    PROJECT_ACTIONS.CREATE_TASK, 
    PROJECT_ACTIONS.UPDATE_TASK,
    PROJECT_ACTIONS.INVITE_MEMBER,
    PROJECT_ACTIONS.LEAVE  
  ])
});

export default ROLE_PERMISSIONS;